import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/
export const metadata: Metadata = {
  title: "Mukesh Kumar | Portfolio",
  description: "Mukesh Kumar - Full Stack Web Developer Portfolio",
  keywords: ["Mukesh Kumar", "Full Stack Developer", "Next.js Developer", "React Developer", "Web Development", "Laravel Developer"],
  authors: [{ name: "Mukesh Kumar", url: "https://mukeshportfolio.com" }],
  creator: "Mukesh Kumar",
  themeColor: "#1a1a1a",
  robots: "index, follow",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`scroll-smooth  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
